services:
  app:
    build: .
    container_name: app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nvk.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - 5430:80
    depends_on:
      - db

volumes:
  pg_data:
